version: '3.8'

services:
  # nginx:
  #   container_name: nginx
  #   image: nginx:alpine
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - app
  #     - db
  #   volumes:
  #     - ./scr:/var/www
  #     - ./nginx/conf.d/:/etc/nginx/conf.d
  php:
    container_name: php
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      - database
  database:
    image: mysql:8.0
    container_name: mysql-lucete
    ports:
      - 3307:3006
    volumes:
        - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
  #   ports:
  #     - 6379:6379
  # # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   ports:
  #     - "3400:80"
  #   depends_on:
  #     - db
  # app:
volumes:
  db-data: ~